directories:
  output: dist
  buildResources: resources
appId: com.yourdoamnin.yourapp
files:
  - filter:
      - assets/**/*
      - build/**/*
      - capacitor.config.*
      - app/**/*
publish:
  provider: github
  publishAutoUpdate: false
extends: null
nsis: {}
win:
  target: nsis
  icon: assets/appIcon.ico
electronVersion: 13.1.9
